version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
