# File Browser
# Usuário: admin
# Senha: admin
version: '3.7'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname: filebrowser
    ports:
      - 80:80
    volumes:
      - ./data/config/database.db:/database.db
      - ./data/home:/srv
    restart: unless-stopped
