version: '3.7'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "xyz@123cba"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql
    