version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      #MYSQL_DATABASE: mysql_db
      #MYSQL_USER: mysql_user
      #MYSQL_PASSWORD: mysql_pass
    command: --default-authentication-plugin=mysql_native_password
    user: 1000:1000
    volumes:
      - ./data:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 80:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 123456
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
