---
services:
  samba:
    image: rrapsag/samba:latest
    container_name: samba
    ports:
      - "445:445/tcp"
    environment:
      USER: samba
      PASS: samba
      #UID: 1000 # optional
      #GID: 1000 # optional
    volumes:
      - ./storage:/storage
