version: '3.7'

services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    #environment:
    #  GITLAB_OMNIBUS_CONFIG: |
    #    external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./data/config:/etc/gitlab
      - ./data/logs:/var/log/gitlab
      - ./data/gitlab:/var/opt/gitlab'
