version: '3.7'

services:
  homer:
    image: b4bz/homer
    container_name: homer
    hostname: homer
    ports:
      - 8080:8080
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./data:/www/assets
    restart: unless-stopped
