version: "3.7"
 
services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/:/data/db
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    depends_on:
      - db
    ports:
      - 80:3000
    volumes:
      - ./.client:/data/db
