version: '3.7'

services:
  whoogle:
    image: benbusby/whoogle-search
    container_name: whoogle
    hostname: whoogle
    ports:
      - 5000:5000
    environment:
      - WHOOGLE_CONFIG_LANGUAGE=$LANG
    #  - WHOOGLE_USER=admin
    #  - WHOOGLE_PASS=passwd
    restart: unless-stopped
