version: '3.7'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: '123456'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
    volumes:
      - './config/pihole/:/etc/pihole/'
      - './config/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    #restart: unless-stopped
