version: '3.7'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./data/nextcloud:/var/www/html
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./data/mysql:/var/lib/mysql
