version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  pg:
    image: dockage/phppgadmin:latest
    container_name: phppgadmin
    ports:
      - 80:80
    environment:
      PHP_PG_ADMIN_SERVER_DESC: PostgreSQL
      PHP_PG_ADMIN_SERVER_HOST: db
      PHP_PG_ADMIN_SERVER_PORT: 5432
      PHP_PG_ADMIN_SERVER_SSL_MODE: allow
      PHP_PG_ADMIN_SERVER_DEFAULT_DB: template1
      PHP_PG_ADMIN_SERVER_PG_DUMP_PATH: /usr/bin/pg_dump
      PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH: /usr/bin/pg_dumpall

      PHP_PG_ADMIN_DEFAULT_LANG: auto
      PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY: "false"
      PHP_PG_ADMIN_SHOW_ADVANCED: "false"
      PHP_PG_ADMIN_SHOW_SYSTEM: "false"
