version: '3.7'

services:
  emby:
    image: emby/embyserver:latest
    container_name: media
    hostname: emby
    ports:
      - 80:8096
    environment:
      UID: 1000
      GID: 100
      GIDLIST: 100
      TZ: "America/Sao_Paulo"
    volumes:
      - ./config:/config
      - ./media:/media
