---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    ports:
      - 80:80
      - 443:443
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Sao_Paulo"
    volumes:
      - ./config:/config
    restart: unless-stopped
